//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.34011
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace FitAndGym.Resources {
    using System;
    
    
    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option, or rebuild your VS project.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "4.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    public class AppResources {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal AppResources() {
        }
        
        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("FitAndGym.Resources.AppResources", typeof(AppResources).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to About app.
        /// </summary>
        public static string AboutSentence {
            get {
                return ResourceManager.GetString("AboutSentence", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to create new.
        /// </summary>
        public static string AddExerciseAppBar {
            get {
                return ResourceManager.GetString("AddExerciseAppBar", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to If you have noticed any lack of functionality or any bug of the Fit&amp;Gym app, let me know about it.
        ///
        ///Your information won&apos;t be ignored.
        ///
        ///PS. Rates and comments will be welcome ;).
        /// </summary>
        public static string AdditionalContentOfAboutBox {
            get {
                return ResourceManager.GetString("AdditionalContentOfAboutBox", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to create new.
        /// </summary>
        public static string AddTrainingAppBar {
            get {
                return ResourceManager.GetString("AddTrainingAppBar", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to new training.
        /// </summary>
        public static string AddTrainingPageHeader {
            get {
                return ResourceManager.GetString("AddTrainingPageHeader", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Reps.
        /// </summary>
        public static string AmountOfRepsCaptionOnTheMainPage {
            get {
                return ResourceManager.GetString("AmountOfRepsCaptionOnTheMainPage", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Sets.
        /// </summary>
        public static string AmountOfSetsCaptionOnTheMainPage {
            get {
                return ResourceManager.GetString("AmountOfSetsCaptionOnTheMainPage", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to You have to bind 1 exercise at least to the training!.
        /// </summary>
        public static string AnyExercisesAreRequiredNotification {
            get {
                return ResourceManager.GetString("AnyExercisesAreRequiredNotification", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Fit&amp;Gym.
        /// </summary>
        public static string ApplicationTitle {
            get {
                return ResourceManager.GetString("ApplicationTitle", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to exercises.
        /// </summary>
        public static string AttachExercisesHeaderText {
            get {
                return ResourceManager.GetString("AttachExercisesHeaderText", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Calendar.
        /// </summary>
        public static string CalendarPivotHeader {
            get {
                return ResourceManager.GetString("CalendarPivotHeader", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Are you sure you want to exit the application?.
        /// </summary>
        public static string ConfirmationExitActionAlertContent {
            get {
                return ResourceManager.GetString("ConfirmationExitActionAlertContent", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Confirmation alert.
        /// </summary>
        public static string ConfirmationExitActionAlertHeader {
            get {
                return ResourceManager.GetString("ConfirmationExitActionAlertHeader", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Exercises of the training.
        /// </summary>
        public static string ConnectedExercisesMessageBoxHeader {
            get {
                return ResourceManager.GetString("ConnectedExercisesMessageBoxHeader", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Clone the training.
        /// </summary>
        public static string CopyTrainingMenuItemText {
            get {
                return ResourceManager.GetString("CopyTrainingMenuItemText", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to szbartnik@gmail.com.
        /// </summary>
        public static string CreatorEmail {
            get {
                return ResourceManager.GetString("CreatorEmail", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Szymon Bartnik.
        /// </summary>
        public static string CreatorNameAndSurname {
            get {
                return ResourceManager.GetString("CreatorNameAndSurname", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Trainings that will be deleted.
        /// </summary>
        public static string DatesOfTrainingsThatWillBeDeleted {
            get {
                return ResourceManager.GetString("DatesOfTrainingsThatWillBeDeleted", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to days.
        /// </summary>
        public static string DaysCaption {
            get {
                return ResourceManager.GetString("DaysCaption", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Delete old trainings.
        /// </summary>
        public static string DeleteOldTrainingsMenuText {
            get {
                return ResourceManager.GetString("DeleteOldTrainingsMenuText", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Delete old trainings.
        /// </summary>
        public static string DeleteTrainingsByDateHeader {
            get {
                return ResourceManager.GetString("DeleteTrainingsByDateHeader", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Delete.
        /// </summary>
        public static string DeleteWord {
            get {
                return ResourceManager.GetString("DeleteWord", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Here you can delete old trainings if you find your training list hard to read because of many items on the list.
        ///
        ///Select a date to which you want to delete all trainings from local database.
        ///
        ///Understand as: .
        /// </summary>
        public static string DescriptionDeleteTrainingsByDate {
            get {
                return ResourceManager.GetString("DescriptionDeleteTrainingsByDate", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Designed and created by.
        /// </summary>
        public static string DesignedAndCreatedBySentence {
            get {
                return ResourceManager.GetString("DesignedAndCreatedBySentence", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to discard.
        /// </summary>
        public static string DiscardChangesAppBar {
            get {
                return ResourceManager.GetString("DiscardChangesAppBar", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Duration (min.).
        /// </summary>
        public static string Duration2CaptionOnTheMainPage {
            get {
                return ResourceManager.GetString("Duration2CaptionOnTheMainPage", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Duration
        ///(minutes).
        /// </summary>
        public static string DurationCaptionOnTheMainPage {
            get {
                return ResourceManager.GetString("DurationCaptionOnTheMainPage", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Edit.
        /// </summary>
        public static string EditWord {
            get {
                return ResourceManager.GetString("EditWord", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to End date of cloning of trainings can&apos;t be less than the start date of the training.
        /// </summary>
        public static string EndDateCannotBeBeforeStartDate {
            get {
                return ResourceManager.GetString("EndDateCannotBeBeforeStartDate", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to The date of end of cloning trainings.
        /// </summary>
        public static string EndDateOfCloningText {
            get {
                return ResourceManager.GetString("EndDateOfCloningText", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to edit exercise.
        /// </summary>
        public static string ExercisePageTitleEditMode {
            get {
                return ResourceManager.GetString("ExercisePageTitleEditMode", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to new exercise.
        /// </summary>
        public static string ExercisePageTitleNewMode {
            get {
                return ResourceManager.GetString("ExercisePageTitleNewMode", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Exercises.
        /// </summary>
        public static string ExercisesPivotHeader {
            get {
                return ResourceManager.GetString("ExercisesPivotHeader", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Name property is required!.
        /// </summary>
        public static string ExNamePropertyIsRequiredNotification {
            get {
                return ResourceManager.GetString("ExNamePropertyIsRequiredNotification", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to everyday.
        /// </summary>
        public static string FrequenceEveryDay {
            get {
                return ResourceManager.GetString("FrequenceEveryDay", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to once only.
        /// </summary>
        public static string FrequenceWithoutRepeats {
            get {
                return ResourceManager.GetString("FrequenceWithoutRepeats", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to help.
        /// </summary>
        public static string HelpButtonInCalendarAppBar {
            get {
                return ResourceManager.GetString("HelpButtonInCalendarAppBar", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Days with bound trainings are marked by your phone&apos;s current theme colour.
        ///
        ///The numbers on these days express total sums of exercises of every training day..
        /// </summary>
        public static string HelpContentInCalendar {
            get {
                return ResourceManager.GetString("HelpContentInCalendar", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Later you will be able to clone your trainings (if you do it regularly for example).
        ///
        ///If you want to do it, after saving the current training tap &amp; hold your training on &quot;Trainings&quot; page and everything will be clear then..
        /// </summary>
        public static string HelpContentInManageTraining {
            get {
                return ResourceManager.GetString("HelpContentInManageTraining", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Help &amp; Info.
        /// </summary>
        public static string HelpHeaderInCalendar {
            get {
                return ResourceManager.GetString("HelpHeaderInCalendar", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Help &amp; Info.
        /// </summary>
        public static string HelpHeaderInManageTraining {
            get {
                return ResourceManager.GetString("HelpHeaderInManageTraining", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to help.
        /// </summary>
        public static string HelpInTrainingPageAppBar {
            get {
                return ResourceManager.GetString("HelpInTrainingPageAppBar", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Incoming .
        /// </summary>
        public static string IncomingTrainingsPivotHeader {
            get {
                return ResourceManager.GetString("IncomingTrainingsPivotHeader", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to about app.
        /// </summary>
        public static string InfoAppBar {
            get {
                return ResourceManager.GetString("InfoAppBar", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Intensity.
        /// </summary>
        public static string IntensityCaptionOnTheMainPage {
            get {
                return ResourceManager.GetString("IntensityCaptionOnTheMainPage", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to High.
        /// </summary>
        public static string IntensityHigh {
            get {
                return ResourceManager.GetString("IntensityHigh", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Low.
        /// </summary>
        public static string IntensityLow {
            get {
                return ResourceManager.GetString("IntensityLow", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Medium.
        /// </summary>
        public static string IntensityMedium {
            get {
                return ResourceManager.GetString("IntensityMedium", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Very High.
        /// </summary>
        public static string IntensityVeryHigh {
            get {
                return ResourceManager.GetString("IntensityVeryHigh", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Very Low.
        /// </summary>
        public static string IntensityVeryLow {
            get {
                return ResourceManager.GetString("IntensityVeryLow", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Intervals between trainings (days).
        /// </summary>
        public static string IntervalsBetweenTrainings {
            get {
                return ResourceManager.GetString("IntervalsBetweenTrainings", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Duration.
        /// </summary>
        public static string NewExerciseDurationText {
            get {
                return ResourceManager.GetString("NewExerciseDurationText", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Intensity.
        /// </summary>
        public static string NewExerciseIntensityText {
            get {
                return ResourceManager.GetString("NewExerciseIntensityText", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Name.
        /// </summary>
        public static string NewExerciseNameText {
            get {
                return ResourceManager.GetString("NewExerciseNameText", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Additional info.
        /// </summary>
        public static string NewExerciseOtherInfoHeader {
            get {
                return ResourceManager.GetString("NewExerciseOtherInfoHeader", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Place here an additional info about the exercise....
        /// </summary>
        public static string NewExerciseOtherInfoPlaceholder {
            get {
                return ResourceManager.GetString("NewExerciseOtherInfoPlaceholder", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Number of reps.
        /// </summary>
        public static string NewExerciseRepsText {
            get {
                return ResourceManager.GetString("NewExerciseRepsText", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Number of sets.
        /// </summary>
        public static string NewExerciseSetsText {
            get {
                return ResourceManager.GetString("NewExerciseSetsText", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Duration.
        /// </summary>
        public static string NewTrainingDurationText {
            get {
                return ResourceManager.GetString("NewTrainingDurationText", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Name.
        /// </summary>
        public static string NewTrainingeNameText {
            get {
                return ResourceManager.GetString("NewTrainingeNameText", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Water (liters).
        /// </summary>
        public static string NewTrainingHydrationText {
            get {
                return ResourceManager.GetString("NewTrainingHydrationText", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Additional info.
        /// </summary>
        public static string NewTrainingOtherInfoHeader {
            get {
                return ResourceManager.GetString("NewTrainingOtherInfoHeader", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Place here an additional info about the training....
        /// </summary>
        public static string NewTrainingOtherInfoPlaceholder {
            get {
                return ResourceManager.GetString("NewTrainingOtherInfoPlaceholder", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to NO.
        /// </summary>
        public static string No {
            get {
                return ResourceManager.GetString("No", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Number of trainings that will be added.
        /// </summary>
        public static string NumOfTrainingsThatWillBeAdded {
            get {
                return ResourceManager.GetString("NumOfTrainingsThatWillBeAdded", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Older than.
        /// </summary>
        public static string OlderThan {
            get {
                return ResourceManager.GetString("OlderThan", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Other info.
        /// </summary>
        public static string OtherInfo2CaptionOnTheMainPage {
            get {
                return ResourceManager.GetString("OtherInfo2CaptionOnTheMainPage", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Other
        ///info.
        /// </summary>
        public static string OtherInfoCaptionOnTheMainPage {
            get {
                return ResourceManager.GetString("OtherInfoCaptionOnTheMainPage", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to accept.
        /// </summary>
        public static string ProceedCloningAppBar {
            get {
                return ResourceManager.GetString("ProceedCloningAppBar", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to execute.
        /// </summary>
        public static string ProceedDeleteByDateAppBar {
            get {
                return ResourceManager.GetString("ProceedDeleteByDateAppBar", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to rate app.
        /// </summary>
        public static string RateAppBar {
            get {
                return ResourceManager.GetString("RateAppBar", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to LeftToRight.
        /// </summary>
        public static string ResourceFlowDirection {
            get {
                return ResourceManager.GetString("ResourceFlowDirection", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to en-US.
        /// </summary>
        public static string ResourceLanguage {
            get {
                return ResourceManager.GetString("ResourceLanguage", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to save.
        /// </summary>
        public static string SaveChangesAppBar {
            get {
                return ResourceManager.GetString("SaveChangesAppBar", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Set the intervals between trainings.
        /// </summary>
        public static string SetFrequencyOfTrainingMessage {
            get {
                return ResourceManager.GetString("SetFrequencyOfTrainingMessage", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Date.
        /// </summary>
        public static string StartTimeCaption {
            get {
                return ResourceManager.GetString("StartTimeCaption", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Date of training property is required!.
        /// </summary>
        public static string StartTimeOfTrainingPropertyIsRequiredNotification {
            get {
                return ResourceManager.GetString("StartTimeOfTrainingPropertyIsRequiredNotification", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to The date of end of cloning trainings.
        /// </summary>
        public static string TheDateOfEndOfCloningTrainings {
            get {
                return ResourceManager.GetString("TheDateOfEndOfCloningTrainings", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to ago.
        /// </summary>
        public static string TimeConverterAgoWord {
            get {
                return ResourceManager.GetString("TimeConverterAgoWord", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to d.
        /// </summary>
        public static string TimeConverterDayWord {
            get {
                return ResourceManager.GetString("TimeConverterDayWord", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to h.
        /// </summary>
        public static string TimeConverterHourWord {
            get {
                return ResourceManager.GetString("TimeConverterHourWord", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to in.
        /// </summary>
        public static string TimeConverterInWord {
            get {
                return ResourceManager.GetString("TimeConverterInWord", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to m.
        /// </summary>
        public static string TimeConverterMinuteWord {
            get {
                return ResourceManager.GetString("TimeConverterMinuteWord", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to s.
        /// </summary>
        public static string TimeConverterSecondWord {
            get {
                return ResourceManager.GetString("TimeConverterSecondWord", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Clone trainings.
        /// </summary>
        public static string TrainingCopyActionCheckBoxCaption {
            get {
                return ResourceManager.GetString("TrainingCopyActionCheckBoxCaption", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Clone the training.
        /// </summary>
        public static string TrainingCopyActionHeader {
            get {
                return ResourceManager.GetString("TrainingCopyActionHeader", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Repeat training.
        /// </summary>
        public static string TrainingCopyActionsFrequency {
            get {
                return ResourceManager.GetString("TrainingCopyActionsFrequency", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Trainings.
        /// </summary>
        public static string TrainingDaysPivotHeader {
            get {
                return ResourceManager.GetString("TrainingDaysPivotHeader", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to edit training.
        /// </summary>
        public static string TrainingPageTitleEditMode {
            get {
                return ResourceManager.GetString("TrainingPageTitleEditMode", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to new training.
        /// </summary>
        public static string TrainingPageTitleNewMode {
            get {
                return ResourceManager.GetString("TrainingPageTitleNewMode", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Trainings of the selected day.
        /// </summary>
        public static string TrainingsOfTheDay {
            get {
                return ResourceManager.GetString("TrainingsOfTheDay", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to The training will be cloned to following dates:.
        /// </summary>
        public static string TrainingsThatWillBeAdded {
            get {
                return ResourceManager.GetString("TrainingsThatWillBeAdded", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Type the name of exercise....
        /// </summary>
        public static string TypeNameOfExercisePlaceholder {
            get {
                return ResourceManager.GetString("TypeNameOfExercisePlaceholder", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Type the name of training....
        /// </summary>
        public static string TypeNameOfTrainingPlaceholder {
            get {
                return ResourceManager.GetString("TypeNameOfTrainingPlaceholder", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to update.
        /// </summary>
        public static string UpdateChangesAppBar {
            get {
                return ResourceManager.GetString("UpdateChangesAppBar", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Validation Error.
        /// </summary>
        public static string ValidationErrorTitle {
            get {
                return ResourceManager.GetString("ValidationErrorTitle", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to &quot;trainings with start date (+ optional duration of the training) older than selected date will be deleted permanently from your local database&quot;.
        /// </summary>
        public static string WarningDeleteTrainingsByDate {
            get {
                return ResourceManager.GetString("WarningDeleteTrainingsByDate", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Water
        ///(liters).
        /// </summary>
        public static string WaterCaptionOnTheMainPage {
            get {
                return ResourceManager.GetString("WaterCaptionOnTheMainPage", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to YES.
        /// </summary>
        public static string Yes {
            get {
                return ResourceManager.GetString("Yes", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Simultaneously you can&apos;t add more than 30 clones of trainings.
        /// </summary>
        public static string YouCannotInsertMoreThanxClonesSimu {
            get {
                return ResourceManager.GetString("YouCannotInsertMoreThanxClonesSimu", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to You can&apos;t clone training to the past.
        /// </summary>
        public static string YouCannotInsertTrainingsInThePast {
            get {
                return ResourceManager.GetString("YouCannotInsertTrainingsInThePast", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to The range is too short to insert any clones..
        /// </summary>
        public static string YouHaveToAddMoreThanZeroClones {
            get {
                return ResourceManager.GetString("YouHaveToAddMoreThanZeroClones", resourceCulture);
            }
        }
    }
}
