//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.34003
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace FitAndGym.Resources {
    using System;
    
    
    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option, or rebuild your VS project.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "4.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    public class AppResources {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal AppResources() {
        }
        
        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("FitAndGym.Resources.AppResources", typeof(AppResources).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to create new.
        /// </summary>
        public static string AddExerciseAppBar {
            get {
                return ResourceManager.GetString("AddExerciseAppBar", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to create new.
        /// </summary>
        public static string AddTrainingAppBar {
            get {
                return ResourceManager.GetString("AddTrainingAppBar", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to new training.
        /// </summary>
        public static string AddTrainingPageHeader {
            get {
                return ResourceManager.GetString("AddTrainingPageHeader", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Fit&amp;Gym.
        /// </summary>
        public static string ApplicationTitle {
            get {
                return ResourceManager.GetString("ApplicationTitle", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Delete.
        /// </summary>
        public static string DeleteWord {
            get {
                return ResourceManager.GetString("DeleteWord", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to discard.
        /// </summary>
        public static string DiscardChangesAppBar {
            get {
                return ResourceManager.GetString("DiscardChangesAppBar", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Edit.
        /// </summary>
        public static string EditWord {
            get {
                return ResourceManager.GetString("EditWord", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to edit exercise.
        /// </summary>
        public static string ExercisePageTitleEditMode {
            get {
                return ResourceManager.GetString("ExercisePageTitleEditMode", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to new exercise.
        /// </summary>
        public static string ExercisePageTitleNewMode {
            get {
                return ResourceManager.GetString("ExercisePageTitleNewMode", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Exercises.
        /// </summary>
        public static string ExercisesPivotHeader {
            get {
                return ResourceManager.GetString("ExercisesPivotHeader", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Name property is required!.
        /// </summary>
        public static string ExNamePropertyIsRequiredNotification {
            get {
                return ResourceManager.GetString("ExNamePropertyIsRequiredNotification", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to In the next step you will be able to set repeats for your new trening..
        /// </summary>
        public static string HelpContentInManageTraining {
            get {
                return ResourceManager.GetString("HelpContentInManageTraining", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Help &amp; Info.
        /// </summary>
        public static string HelpHeaderInManageTraining {
            get {
                return ResourceManager.GetString("HelpHeaderInManageTraining", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to help.
        /// </summary>
        public static string HelpInTrainingPageAppBar {
            get {
                return ResourceManager.GetString("HelpInTrainingPageAppBar", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to High.
        /// </summary>
        public static string IntensityHigh {
            get {
                return ResourceManager.GetString("IntensityHigh", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Low.
        /// </summary>
        public static string IntensityLow {
            get {
                return ResourceManager.GetString("IntensityLow", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Medium.
        /// </summary>
        public static string IntensityMedium {
            get {
                return ResourceManager.GetString("IntensityMedium", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Very High.
        /// </summary>
        public static string IntensityVeryHigh {
            get {
                return ResourceManager.GetString("IntensityVeryHigh", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Very Low.
        /// </summary>
        public static string IntensityVeryLow {
            get {
                return ResourceManager.GetString("IntensityVeryLow", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Duration.
        /// </summary>
        public static string NewExerciseDurationText {
            get {
                return ResourceManager.GetString("NewExerciseDurationText", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Intensity.
        /// </summary>
        public static string NewExerciseIntensityText {
            get {
                return ResourceManager.GetString("NewExerciseIntensityText", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Name.
        /// </summary>
        public static string NewExerciseNameText {
            get {
                return ResourceManager.GetString("NewExerciseNameText", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Additional info.
        /// </summary>
        public static string NewExerciseOtherInfoHeader {
            get {
                return ResourceManager.GetString("NewExerciseOtherInfoHeader", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Place here an additional info about the exercise....
        /// </summary>
        public static string NewExerciseOtherInfoPlaceholder {
            get {
                return ResourceManager.GetString("NewExerciseOtherInfoPlaceholder", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Number of reps.
        /// </summary>
        public static string NewExerciseRepsText {
            get {
                return ResourceManager.GetString("NewExerciseRepsText", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Number of sets.
        /// </summary>
        public static string NewExerciseSetsText {
            get {
                return ResourceManager.GetString("NewExerciseSetsText", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Duration.
        /// </summary>
        public static string NewTrainingDurationText {
            get {
                return ResourceManager.GetString("NewTrainingDurationText", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Name.
        /// </summary>
        public static string NewTrainingeNameText {
            get {
                return ResourceManager.GetString("NewTrainingeNameText", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Hydration.
        /// </summary>
        public static string NewTrainingHydrationText {
            get {
                return ResourceManager.GetString("NewTrainingHydrationText", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Additional info.
        /// </summary>
        public static string NewTrainingOtherInfoHeader {
            get {
                return ResourceManager.GetString("NewTrainingOtherInfoHeader", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Place here an additional info about the training....
        /// </summary>
        public static string NewTrainingOtherInfoPlaceholder {
            get {
                return ResourceManager.GetString("NewTrainingOtherInfoPlaceholder", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to LeftToRight.
        /// </summary>
        public static string ResourceFlowDirection {
            get {
                return ResourceManager.GetString("ResourceFlowDirection", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to en-US.
        /// </summary>
        public static string ResourceLanguage {
            get {
                return ResourceManager.GetString("ResourceLanguage", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to save.
        /// </summary>
        public static string SaveChangesAppBar {
            get {
                return ResourceManager.GetString("SaveChangesAppBar", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Date.
        /// </summary>
        public static string StartTimeCaption {
            get {
                return ResourceManager.GetString("StartTimeCaption", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Date of training property is required!.
        /// </summary>
        public static string StartTimeOfTrainingPropertyIsRequiredNotification {
            get {
                return ResourceManager.GetString("StartTimeOfTrainingPropertyIsRequiredNotification", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Trainings.
        /// </summary>
        public static string TrainingDaysPivotHeader {
            get {
                return ResourceManager.GetString("TrainingDaysPivotHeader", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to edit training.
        /// </summary>
        public static string TrainingPageTitleEditMode {
            get {
                return ResourceManager.GetString("TrainingPageTitleEditMode", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to new training.
        /// </summary>
        public static string TrainingPageTitleNewMode {
            get {
                return ResourceManager.GetString("TrainingPageTitleNewMode", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Type the name of exercise....
        /// </summary>
        public static string TypeNameOfExercisePlaceholder {
            get {
                return ResourceManager.GetString("TypeNameOfExercisePlaceholder", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Type the name of training....
        /// </summary>
        public static string TypeNameOfTrainingPlaceholder {
            get {
                return ResourceManager.GetString("TypeNameOfTrainingPlaceholder", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to update.
        /// </summary>
        public static string UpdateChangesAppBar {
            get {
                return ResourceManager.GetString("UpdateChangesAppBar", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Validation Error.
        /// </summary>
        public static string ValidationErrorTitle {
            get {
                return ResourceManager.GetString("ValidationErrorTitle", resourceCulture);
            }
        }
    }
}
